# Generated by Django 4.2.10 on 2024-03-01 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "company_id",
                    models.CharField(editable=False, max_length=555, unique=True),
                ),
                ("company_name", models.CharField(db_index=True, max_length=25)),
                ("short_code", models.CharField(blank=True, max_length=8, null=True)),
                ("location", models.CharField(blank=True, max_length=155, null=True)),
                ("address", models.TextField(blank=True, max_length=155, null=True)),
                ("description", models.TextField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_deleted", models.BooleanField(default=False)),
                (
                    "employee_id",
                    models.CharField(editable=False, max_length=555, unique=True),
                ),
                ("employee_name", models.CharField(db_index=True, max_length=555)),
                ("employee_email", models.EmailField(max_length=254)),
                (
                    "employee_mobile_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "company_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="employee_company",
                        to="core.company",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
